default_platform(:android)

platform :android do

  desc 'Upload App to CHPlay.'
  lane :playstore do
    # ...
    upload_to_play_store(
      track: 'internal',
      package_name: ENV['PACKAGE_NAME'],
      json_key: ENV['SERVICE_ACCOUNT_JSON'],
      aab: "./fastlane/aab/#{ENV['ENV']}/app-#{ENV['ENV']}.aab"
    )
  end

  desc 'Upload App to App Center.'
  lane :uploadToAppcenter do
    appcenter_upload(
      api_token: ENV["APPCENTER_API_TOKEN"],
      owner_name: ENV["APPCENTER_OWNER_NAME"],
      app_name: ENV["APPCENTER_APP_NAME"],
      destinations: "#{ENV['ENV']}",
      file: "./fastlane/aab/#{ENV['ENV']}/app-#{ENV['ENV']}.aab"
    )
  end

  desc 'Build Application'
  lane :build do
    environment = "#{ENV['ENV']}"
    if environment == 'development'
      buildNumber = appcenter_fetch_version_number(
        api_token: ENV["APPCENTER_API_TOKEN"],
        owner_name: ENV["APPCENTER_OWNER_NAME"],
        app_name: ENV["APPCENTER_APP_NAME"],
      )
      versionName = '0.0.1'
      versionCode = buildNumber['build_number'].to_i + 1
    elsif environment == 'staging'
      buildNumber = appcenter_fetch_version_number(
        api_token: ENV["APPCENTER_API_TOKEN"],
        owner_name: ENV["APPCENTER_OWNER_NAME"],
        app_name: ENV["APPCENTER_APP_NAME"],
      )
      versionName = ENV['VERSION']
      versionCode = buildNumber['build_number'].to_i + 1
    elsif environment == 'production'
      buildNumber = google_play_track_version_codes(
        track: 'internal',
        package_name: ENV['PACKAGE_NAME']
      )
      versionName = ENV['VERSION']
      versionCode = buildNumber[0].to_i + 1
    end
    puts "Version code:#{versionCode}"
    puts "Version name:#{versionName}"

    gradle(task: 'clean', project_dir: './')

    gradle(
      task: 'bundle',
      build_type: "#{environment}".capitalize,
      project_dir: './',
      properties: {
        "versionCode" => versionCode,
        "versionName" => versionName,
      })

    copy_artifacts(
      artifacts: ["*/build/outputs/bundle/#{environment}/*.aab"],
      target_path: "./fastlane/aab/#{environment}"
    )
    copy_artifacts(
      artifacts: ["*/build/outputs/apk/#{environment}/*.json"],
      target_path: "./fastlane/apk/#{environment}"
    )
  end

  desc "Build and deploy a new build "
  lane :buildAndDeploy do
    build

    if ENV['ENV'] == "development" || ENV['ENV'] == "staging"
      uploadToAppcenter
    elsif ENV['ENV'] == "production"
      playstore
    end
  end
end
